import types
import unittest

from gcode.parser import parse, parse_line, strip_comment, GcodeError


class Comments(unittest.TestCase):
    def test_semicolons_start_a_comment(self):
        self.assertEqual(strip_comment("G1 X10 ; draw the line"), "G1 X10")

    def test_parenthesised_remarks_are_removed_wherever_they_sit(self):
        # The remark leaves a space behind rather than joining its neighbours,
        # so the words either side stay separate. How many spaces is nobody's
        # business; what survives is.
        self.assertEqual(
            strip_comment("G1 (here) X10 (and here) Y5").split(),
            ["G1", "X10", "Y5"],
        )

    def test_an_unclosed_remark_swallows_the_rest_of_the_line(self):
        self.assertEqual(strip_comment("G1 X10 (oops"), "G1 X10")

    def test_a_line_that_is_only_a_comment_has_no_command(self):
        self.assertIsNone(parse_line("; generated by Polargraph"))
        self.assertIsNone(parse_line("   "))


class Lines(unittest.TestCase):
    def test_a_move_carries_its_words(self):
        command = parse_line("G1 X30 Y40 Z-1.5 F1200")

        self.assertEqual(command.kind, "G")
        self.assertEqual(command.code, 1)
        self.assertEqual(command.words, {"X": 30.0, "Y": 40.0, "Z": -1.5, "F": 1200.0})

    def test_lower_case_is_accepted(self):
        self.assertEqual(parse_line("g1 x10").words, {"X": 10.0})

    def test_the_app_s_own_output_parses(self):
        for line in ("G90", "G21", "G0 X10 Y20 F3000", "G1 X30 Y40",
                     "G28", "M0 ; change pen: Layer 1", "M30"):
            self.assertIsNotNone(parse_line(line), line)


class Refusals(unittest.TestCase):
    """A plotter that ignores a word it does not know draws the wrong picture."""

    def test_an_unknown_word_is_refused(self):
        with self.assertRaises(GcodeError):
            parse_line("G1 Q5")

    def test_an_unsupported_command_is_refused(self):
        with self.assertRaises(GcodeError):
            parse_line("G5 X1")

    def test_words_with_no_command_are_refused(self):
        # Modal repetition of the last G is common in other dialects and is not
        # something this writer emits, so accepting it would be guessing.
        with self.assertRaises(GcodeError):
            parse_line("X10 Y10")

    def test_two_commands_on_one_line_are_refused(self):
        with self.assertRaises(GcodeError):
            parse_line("G1 G2 X1")

    def test_a_word_with_no_number_is_refused(self):
        with self.assertRaises(GcodeError):
            parse_line("G1 X")

    def test_a_fractional_command_number_is_refused(self):
        with self.assertRaises(GcodeError):
            parse_line("G1.5 X1")

    def test_the_error_says_which_line(self):
        with self.assertRaises(GcodeError) as caught:
            parse_line("G1 Q5", 42)

        self.assertEqual(caught.exception.line_number, 42)
        self.assertIn("42", str(caught.exception))


class Streaming(unittest.TestCase):
    def test_parsing_is_lazy(self):
        # Plot files are routinely larger than the Pico's RAM, so nothing may
        # read ahead. Feeding a source that records what it was asked for shows
        # the parser taking one line at a time.
        read = []

        def source():
            for line in ("G90", "G1 X1", "G1 X2", "G1 X3"):
                read.append(line)
                yield line

        commands = parse(source())
        self.assertIsInstance(commands, types.GeneratorType)
        self.assertEqual(read, [], "nothing read before the first command is asked for")

        next(commands)
        self.assertEqual(len(read), 1)

        next(commands)
        self.assertEqual(len(read), 2)

    def test_line_numbers_count_every_line_including_blank_ones(self):
        commands = list(parse(["; header", "", "G90", "G1 X1"]))
        self.assertEqual([c.line_number for c in commands], [3, 4])


if __name__ == "__main__":
    unittest.main()
