/**
 * Paths → gcode.
 *
 * Emits the dialect in docs/GCODE.md. Output is modal: a word is written only
 * when its value changes, which is both what gcode conventionally looks like
 * and a real saving on files with tens of thousands of moves streaming off an
 * SD card a line at a time.
 */

import { isDegenerate } from '../geom/path.js';

export const DEFAULTS = {
  /** Whether a pen axis is installed. See AD-2. */
  penLift: false,
  /** Drawing feed rate, mm/min. */
  feedRate: 1200,
  /** Travel feed rate, mm/min. */
  travelFeedRate: 3000,
  /** Pen height for travel moves, mm. Only meaningful when penLift is true. */
  travelZ: 0,
  /** Decimal places. 0.001 mm is well under the machine's 0.0125 mm step. */
  precision: 3,
  /** Return to the calibrated home corner before ending. */
  endWithHome: true,
  /** Include a comment header describing the job. */
  header: true,
};

/**
 * Format a number for gcode: fixed precision, trailing zeros trimmed.
 *
 * Negative zero is normalised away — `-0` is valid JavaScript but reads as a
 * mistake in a file a human may open.
 */
export function formatNumber(value, precision = DEFAULTS.precision) {
  if (!Number.isFinite(value)) return '0';

  const fixed = value.toFixed(precision);
  const trimmed = fixed.includes('.')
    ? fixed.replace(/0+$/, '').replace(/\.$/, '')
    : fixed;

  return trimmed === '-0' ? '0' : trimmed;
}

/**
 * Tracks which axis and feed values the machine already holds, so only changes
 * are written. Comparing formatted strings rather than raw numbers means a
 * value that rounds to the same output is correctly treated as unchanged.
 */
class ModalState {
  constructor(precision) {
    this.precision = precision;
    this.axes = { X: null, Y: null, Z: null };
    this.feed = null;
  }

  axis(name, value) {
    const text = formatNumber(value, this.precision);
    if (this.axes[name] === text) return null;

    this.axes[name] = text;
    return `${name}${text}`;
  }

  feedRate(value) {
    const text = formatNumber(value, this.precision);
    if (this.feed === text) return null;

    this.feed = text;
    return `F${text}`;
  }
}

/**
 * Words for a move, or null when no axis actually changes.
 *
 * The feed word is only claimed once an axis has changed. Asking the modal
 * state for it unconditionally would record the new feed even on a line the
 * caller then discards, leaving the state believing the machine holds a value
 * it was never sent — and every later feed change silently suppressed.
 */
function moveWords(state, { x, y, z }, feed) {
  const axes = [
    state.axis('X', x),
    state.axis('Y', y),
    state.axis('Z', z),
  ].filter(Boolean);

  if (axes.length === 0) return null;

  const feedWord = state.feedRate(feed);
  return feedWord ? [...axes, feedWord] : axes;
}

/**
 * Write paths as gcode.
 *
 * With `penLift` false — the v1 machine, which has no pen axis — travel moves
 * still mark the paper, so nothing is done to lift between strokes and the
 * `G0` is honest about being a drawn line. With `penLift` true the pen rises to
 * `travelZ` before each travel and returns to the stroke's own depth after.
 */
export function writeGcode(paths, options = {}) {
  const opts = { ...DEFAULTS, ...options };
  const { precision } = opts;

  const drawable = paths.filter((p) => !isDegenerate(p));
  const state = new ModalState(precision);
  const lines = [];

  if (opts.header) {
    lines.push(
      '; Generated by Polargraph',
      `; paths: ${drawable.length}`,
      `; pen lift: ${opts.penLift ? 'yes' : 'no — travel moves mark the paper'}`,
      `; feed: ${formatNumber(opts.feedRate, precision)} mm/min`
    );
  }

  lines.push('G90');

  for (const path of drawable) {
    const points = path.closed
      ? [...path.points, path.points[0]]
      : path.points;

    const [start, ...rest] = points;

    if (opts.penLift) {
      const raise = state.axis('Z', opts.travelZ);
      if (raise) lines.push(`G0 ${raise}`);
    }

    // Travel to the start of the stroke without its Z, so a pen-lift machine
    // stays raised until it has arrived.
    const travelAxes = [
      state.axis('X', start.x),
      state.axis('Y', start.y),
      opts.penLift ? null : state.axis('Z', start.z),
    ].filter(Boolean);

    // A stroke beginning where the last one ended needs no travel at all.
    // Emitting `G0` with only a feed word would be a move that moves nothing.
    if (travelAxes.length > 0) {
      const feedWord = state.feedRate(opts.travelFeedRate);
      lines.push(`G0 ${(feedWord ? [...travelAxes, feedWord] : travelAxes).join(' ')}`);
    }

    if (opts.penLift) {
      const lower = state.axis('Z', start.z);
      if (lower) lines.push(`G1 ${lower} ${state.feedRate(opts.feedRate) ?? ''}`.trim());
    }

    for (const point of rest) {
      const words = moveWords(state, point, opts.feedRate);
      if (words) lines.push(`G1 ${words.join(' ')}`);
    }
  }

  if (opts.penLift && drawable.length > 0) {
    const raise = state.axis('Z', opts.travelZ);
    if (raise) lines.push(`G0 ${raise}`);
  }

  if (opts.endWithHome) lines.push('G28');
  lines.push('M30');

  return `${lines.join('\n')}\n`;
}
