import math
import unittest

import simulator as sim
from motion import kinematics as kin
from motion.planner import Limits


GEOMETRY = kin.Geometry(900, 250, 300, 300, 400)
LIMITS = Limits(max_speed_mm_s=20, acceleration_mm_s2=200, max_segment_mm=1.0)


def square():
    corners = [(20, 20), (280, 20), (280, 380), (20, 380), (20, 20)]
    return [GEOMETRY.to_machine(*c) for c in corners]


def spiral(turns=1200):
    points = []
    for i in range(turns):
        angle = i * 0.08
        radius = 5 + i * 0.11
        points.append(GEOMETRY.to_machine(
            150 + radius * math.cos(angle),
            200 + radius * math.sin(angle),
        ))
    return points


class Geometry(unittest.TestCase):
    """What the steps actually drew, against what was asked for."""

    def test_the_pen_never_leaves_the_line(self):
        path = square()
        trace = sim.run(GEOMETRY, LIMITS, path, start=path[0])

        # Under one step. Anything larger is chord error from segmenting a
        # straight line too coarsely for the belt geometry.
        self.assertLess(sim.deviation(trace, path), kin.MM_PER_STEP)

    def test_a_long_job_does_not_drift(self):
        # The point of deriving every target from the true geometry rather than
        # carrying a remainder forward. Seven thousand segments and most of a
        # million steps later, the gondola is still where it should be.
        path = spiral()
        trace = sim.run(GEOMETRY, LIMITS, path, start=path[0])

        self.assertGreater(len(trace.segments), 5000)
        self.assertLess(sim.endpoint_error(trace, path), kin.MM_PER_STEP / 2)
        self.assertLess(sim.deviation(trace, path), kin.MM_PER_STEP)

    def test_coarse_segmentation_bows_the_line_off_true(self):
        # The failure the segment limit exists to prevent, shown happening.
        path = square()
        coarse = sim.run(GEOMETRY, Limits(max_segment_mm=60.0), path, start=path[0])
        fine = sim.run(GEOMETRY, LIMITS, path, start=path[0])

        self.assertGreater(sim.deviation(coarse, path), sim.deviation(fine, path) * 5)


class Timing(unittest.TestCase):
    def test_the_step_rate_is_beyond_what_python_can_bit_bang(self):
        # The number AD-4 turns on. A MicroPython loop manages a few thousand
        # iterations a second at best, and with jitter a polargraph shows.
        trace = sim.run(GEOMETRY, LIMITS, square(), start=square()[0])

        self.assertGreater(trace.peak_step_rate(), 1000)

    def test_a_faster_job_asks_for_proportionally_more_steps_a_second(self):
        path = square()
        slow = sim.run(GEOMETRY, Limits(max_speed_mm_s=10), path, start=path[0])
        fast = sim.run(GEOMETRY, Limits(max_speed_mm_s=30), path, start=path[0])

        self.assertGreater(fast.peak_step_rate(), slow.peak_step_rate() * 2)
        self.assertLess(fast.seconds, slow.seconds)


class FromGcode(unittest.TestCase):
    def test_the_app_s_gcode_becomes_machine_moves(self):
        lines = [
            "; Generated by Polargraph",
            "G21", "G90",
            "G0 X10 Y20 F3000",
            "G1 X60 Y20 F1200",
            "G1 X60 Y70",
            "M30",
        ]

        moves = sim.moves_from_gcode(GEOMETRY, lines)

        self.assertEqual(len(moves), 3)
        self.assertEqual(moves[0][:2], GEOMETRY.to_machine(10, 20))
        self.assertEqual(moves[1][3], 20.0, "1200 mm/min is 20 mm/s")

    def test_relative_mode_is_followed(self):
        moves = sim.moves_from_gcode(
            GEOMETRY, ["G90", "G0 X10 Y10", "G91", "G1 X5 Y0", "G1 X5 Y0"]
        )

        self.assertEqual(moves[-1][:2], GEOMETRY.to_machine(20, 10))

    def test_a_file_can_be_planned_end_to_end(self):
        lines = ["G21", "G90", "G0 X20 Y20 F3000",
                 "G1 X200 Y20 F1200", "G1 X200 Y300", "M30"]

        moves = sim.moves_from_gcode(GEOMETRY, lines)
        path = [(m[0], m[1]) for m in moves]
        trace = sim.run(GEOMETRY, LIMITS, moves, start=path[0])

        self.assertGreater(len(trace.segments), 400)
        self.assertLess(sim.deviation(trace, path), kin.MM_PER_STEP)


if __name__ == "__main__":
    unittest.main()
