import unittest

from motion import kinematics as kin
from motion.planner import Limits
from motion.stepper import Stepper, RecordingBackend
from motion.pen import NullPen
from job import Job, JobError, IDLE, RUNNING, PAUSED, DONE, ERROR


GEOMETRY = kin.Geometry(900, 250, 300, 300, 400)
LIMITS = Limits(max_speed_mm_s=20, acceleration_mm_s2=200, max_segment_mm=2.0)

PLOT = [
    "; Generated by Polargraph",
    "G21", "G90",
    "G0 X10 Y10 F3000",
    "G1 X100 Y10 F1200",
    "G1 X100 Y100",
    "M30",
]


def make(lines=None, pen=None):
    backend = RecordingBackend()
    pen = pen if pen is not None else NullPen()
    stepper = Stepper(backend, pen)
    job = Job(GEOMETRY, LIMITS, stepper, list(lines if lines else PLOT), pen)

    return job, stepper, backend


class Lifecycle(unittest.TestCase):
    def test_a_job_starts_idle(self):
        job, _, backend = make()

        self.assertEqual(job.state, IDLE)
        self.assertFalse(backend.enabled)

    def test_running_a_plot_reaches_the_end_and_cuts_the_power(self):
        job, stepper, backend = make()
        job.start()

        self.assertEqual(job.run(), DONE)
        self.assertFalse(backend.enabled, "the motors do not hold position after a job")
        self.assertGreater(stepper.segments, 50)

    def test_the_gondola_ends_where_the_file_said(self):
        job, _, _ = make()
        job.start()
        job.run()

        status = job.status()
        self.assertAlmostEqual(status["x"], 100, delta=kin.MM_PER_STEP)
        self.assertAlmostEqual(status["y"], 100, delta=kin.MM_PER_STEP)

    def test_a_finished_job_cannot_be_restarted(self):
        job, _, _ = make()
        job.start()
        job.run()

        with self.assertRaises(JobError):
            job.start()


class Pausing(unittest.TestCase):
    def test_a_pen_swap_pauses_and_waits_to_be_let_go(self):
        # M0 is not a timed wait. It stays paused until something resumes it,
        # which is the whole point of stopping for a pen.
        job, _, _ = make(["G90", "G0 X10 Y10 F3000", "M0 ; change pen",
                          "G1 X50 Y10 F1200", "M30"])
        job.start()

        self.assertEqual(job.run(), PAUSED)
        self.assertEqual(job.pauses, 1)

        self.assertTrue(job.resume())
        self.assertEqual(job.run(), DONE)

    def test_pausing_takes_effect_at_a_command_boundary(self):
        # Not mid-move: the queue drains so the gondola stops somewhere the
        # planner knew about, and resuming is exact.
        job, _, _ = make()
        job.start()
        job.step()

        self.assertTrue(job.pause())
        self.assertEqual(job.state, RUNNING, "not until the next boundary")

        job.step()
        self.assertEqual(job.state, PAUSED)

    def test_a_pause_keeps_position_trustworthy(self):
        job, _, _ = make()
        job.start()
        job.step()
        job.pause()
        job.step()

        self.assertTrue(job.position_trusted)

    def test_resuming_carries_on_from_where_it_stopped(self):
        job, _, _ = make()
        job.start()
        job.step()
        job.pause()
        job.step()

        before = job.status()
        job.resume()
        job.run()
        after = job.status()

        self.assertEqual(job.state, DONE)
        self.assertNotEqual((before["x"], before["y"]), (after["x"], after["y"]))

    def test_pausing_a_job_that_is_not_running_does_nothing(self):
        job, _, _ = make()
        self.assertFalse(job.pause())
        self.assertFalse(job.resume())


class Stopping(unittest.TestCase):
    def test_stopping_loses_position_trust(self):
        # A stop abandons whatever the state machines were part way through,
        # which loses steps. Saying so is AD-5.
        job, _, backend = make()
        job.start()
        job.step()
        job.stop()

        self.assertEqual(job.state, ERROR)
        self.assertFalse(job.position_trusted)
        self.assertFalse(backend.enabled)

    def test_a_driver_fault_is_a_stop_with_a_reason(self):
        job, _, _ = make()
        job.start()
        job.fault("left driver reported a fault")

        self.assertEqual(job.state, ERROR)
        self.assertIn("left driver", job.error)
        self.assertFalse(job.position_trusted)

    def test_a_job_will_not_start_while_position_is_untrusted(self):
        job, _, _ = make()
        job.position_trusted = False

        with self.assertRaises(JobError):
            job.start()


class Errors(unittest.TestCase):
    def test_a_bad_line_stops_the_job_and_says_which(self):
        job, _, backend = make(["G90", "G0 X10 Y10", "G1 Q5", "M30"])
        job.start()

        self.assertEqual(job.run(), ERROR)
        self.assertIn("line 3", job.error)
        self.assertFalse(backend.enabled)

    def test_a_move_off_the_machine_is_refused_before_it_is_attempted(self):
        # Better to stop than to drive the gondola into the frame.
        job, _, _ = make(["G90", "G0 X10 Y10", "G1 X5000 Y10", "M30"])
        job.start()

        self.assertEqual(job.run(), ERROR)
        self.assertIn("reach", job.error)

    def test_inches_are_refused_rather_than_guessed_at(self):
        job, _, _ = make(["G20", "G0 X1 Y1", "M30"])
        job.start()

        self.assertEqual(job.run(), ERROR)
        self.assertIn("millimetres", job.error)


class Dialect(unittest.TestCase):
    def test_relative_moves_are_followed(self):
        job, _, _ = make(["G90", "G0 X10 Y10 F3000", "G91",
                          "G1 X20 Y0 F1200", "G1 X20 Y0", "M30"])
        job.start()
        job.run()

        self.assertAlmostEqual(job.status()["x"], 50, delta=kin.MM_PER_STEP)

    def test_g28_returns_to_the_paper_origin(self):
        # Not a limit-switch seek: a polargraph has no switches, and knows
        # where it is from belt lengths rather than by finding an edge.
        job, _, _ = make(["G90", "G0 X80 Y80 F3000", "G28", "M30"])
        job.start()
        job.run()

        status = job.status()
        self.assertAlmostEqual(status["x"], 0, delta=kin.MM_PER_STEP)
        self.assertAlmostEqual(status["y"], 0, delta=kin.MM_PER_STEP)

    def test_depth_reaches_the_pen(self):
        pen = NullPen()
        job, _, _ = make(["G90", "G0 X10 Y10 F3000", "G1 X60 Y10 Z-1.5 F1200", "M30"], pen)
        job.start()
        job.run()

        self.assertAlmostEqual(pen.position_mm(), -1.5, places=6)
        self.assertAlmostEqual(job.status()["z"], -1.5, places=6)

    def test_m2_ends_a_job_as_well_as_m30(self):
        job, _, _ = make(["G90", "G0 X10 Y10 F3000", "M2"])
        job.start()

        self.assertEqual(job.run(), DONE)

    def test_the_status_is_reported_in_paper_coordinates(self):
        # The app thinks in millimetres from the corner of the sheet and should
        # never have to know where this machine's motors are.
        job, _, _ = make(["G90", "G0 X25 Y35 F3000", "M30"])
        job.start()
        job.run()

        self.assertAlmostEqual(job.status()["x"], 25, delta=kin.MM_PER_STEP)
        self.assertAlmostEqual(job.status()["y"], 35, delta=kin.MM_PER_STEP)


class Streaming(unittest.TestCase):
    def test_the_file_is_read_a_line_at_a_time(self):
        # Plot files are larger than the Pico's RAM. The job may never get
        # ahead of itself.
        read = []

        def source():
            for line in PLOT:
                read.append(line)
                yield line

        backend = RecordingBackend()
        job = Job(GEOMETRY, LIMITS, Stepper(backend, NullPen()), source(), NullPen())
        job.start()

        job.step()
        self.assertLessEqual(len(read), 2)

        job.run()
        self.assertEqual(len(read), len(PLOT))


if __name__ == "__main__":
    unittest.main()


class Recovery(unittest.TestCase):
    """docs/GCODE.md: on any error the firmware pauses, logs it, and reports
    status. There is no auto-recovery; the user aborts or resumes."""

    def test_the_rest_of_the_file_survives_a_bad_line(self):
        # Binning a long plot over one malformed line would be a poor trade,
        # and a line that cannot be read moves nothing, so there is nothing
        # lost to recover from.
        job, _, _ = make(["G90", "G0 X10 Y10 F3000", "G1 Q5",
                          "G1 X60 Y10 F1200", "M30"])
        job.start()

        self.assertEqual(job.run(), ERROR)
        self.assertTrue(job.position_trusted)

        self.assertTrue(job.resume())
        self.assertEqual(job.run(), DONE)
        self.assertAlmostEqual(job.status()["x"], 60, delta=kin.MM_PER_STEP)

    def test_a_stop_is_not_resumable(self):
        # The steps it abandoned are gone, and the machine no longer knows
        # where it is.
        job, _, _ = make()
        job.start()
        job.step()
        job.stop()

        self.assertFalse(job.resume())

    def test_errors_are_written_down(self):
        job, _, _ = make(["G90", "G1 Q5", "M30"])
        job.start()
        job.run()

        self.assertEqual(len(job.log), 1)
        self.assertIn("line 2", job.log[0])
        self.assertIn("Q5", job.log[0])

    def test_resuming_past_an_error_is_written_down_too(self):
        job, _, _ = make(["G90", "G1 Q5", "M30"])
        job.start()
        job.run()
        job.resume()

        self.assertIn("resumed past", job.log[-1])
